// Glossar der Fachbegriffe — gelinkt aus dem UI via .glossary-term[data-term="..."]
// Klick öffnet Modal mit Definition + Formel + Beispiel.

const GLOSSARY = {
  adr: {
    title: 'ADR — Average Daily Rate',
    short: 'Durchschnittlicher Preis pro vermieteter Nacht',
    longDe: 'ADR ist der durchschnittliche Preis den ein Gast pro Nacht zahlt — gemittelt über alle vermieteten Nächte in einem Zeitraum.',
    formula: 'ADR = Brutto-Mieteinnahmen ÷ Anzahl vermieteter Nächte',
    example: 'CHF 35\'000 Einnahmen ÷ 140 vermietete Nächte = CHF 250 ADR',
    caveat: '⚠️ Ein Markt-Durchschnitts-ADR sagt allein nichts aus. Ein 4-Zimmer-Chalet kostet 2-3× mehr als ein Studio. Im KPI-Drill siehst du die Verteilung nach Zimmer-Anzahl.',
  },
  revpar: {
    title: 'RevPAR — Revenue per Available Room',
    short: 'Umsatz pro verfügbarer Vermietungs-Nacht',
    longDe: 'RevPAR kombiniert Preis (ADR) und Auslastung in einer Kennzahl. Verfügbar = die Wohnung könnte vermietet werden, nicht ob sie es war.',
    formula: 'RevPAR = ADR × Auslastung (%)\noder = Jahresumsatz ÷ 365 Tage',
    example: 'ADR CHF 250 × 60% Auslastung = RevPAR CHF 150/Nacht',
    caveat: 'Wenn RevPAR niedrig ist aber ADR hoch → Auslastungsproblem. Wenn ADR niedrig aber RevPAR OK → Markt mit hoher Auslastung.',
  },
  yoy: {
    title: 'YoY — Year-over-Year',
    short: 'Vergleich zum gleichen Zeitraum des Vorjahres',
    longDe: 'YoY (Year-over-Year) misst die Veränderung gegenüber dem identischen Vorjahres-Zeitraum. Eliminiert Saisonalitäts-Effekte: Januar vs Januar, nicht Januar vs Dezember.',
    formula: 'YoY-Δ = (aktuell − Vorjahr) ÷ Vorjahr × 100%',
    example: 'Jan 2026: 8\'000 Logiernächte\nJan 2025: 6\'000 Logiernächte\nYoY = +33%',
  },
  pp: {
    title: 'pp — Prozentpunkte',
    short: 'Absolute Differenz zweier Prozentwerte',
    longDe: 'Prozentpunkte (pp) drücken die rohe Differenz zwischen zwei Prozent-Werten aus — nicht das Verhältnis. Wichtig bei Auslastung und Zinssätzen.',
    formula: 'pp = neuer % − alter %',
    example: 'Auslastung von 60% auf 64% gestiegen = +4 pp\n(NICHT +6.7%, das wäre der relative Anstieg)',
  },
  coc: {
    title: 'CoC — Cash-on-Cash Return',
    short: 'Jährlicher Netto-Cashflow ÷ tatsächlich eingesetztes Eigenkapital',
    longDe: 'CoC ist die wichtigste Kennzahl für Cashflow-Investoren. Sie ignoriert Wertsteigerung und misst nur den tatsächlichen Geldrückfluss auf das eingesetzte Kapital.',
    formula: 'CoC = (NOI − Hypothekarzins) ÷ Eigenkapital × 100%',
    example: 'CHF 25\'000 Cashflow ÷ CHF 250\'000 Eigenkapital = 10% CoC',
    caveat: 'Ab 7% gilt als sehr gut. Vergleich mit 10Y-Swap (~1.35%) — alles über +5 Prozentpunkte Spread ist solide.',
  },
  cap: {
    title: 'Cap Rate — Capitalization Rate',
    short: 'Bruttorendite vor Finanzierung',
    longDe: 'Cap Rate misst die Rendite einer Liegenschaft ohne Hypothek. Wichtig für den Vergleich von Objekten unabhängig von der Finanzierungs-Struktur.',
    formula: 'Cap Rate = NOI ÷ Kaufpreis × 100%',
    example: 'CHF 50\'000 NOI ÷ CHF 1\'250\'000 Kaufpreis = 4% Cap Rate',
    caveat: 'Im Rent-Modus zeigen wir stattdessen den Mietzins-Multiple (STR-Brutto-Monat / Mietzins) — sinnvoller für Arbitrage.',
  },
  noi: {
    title: 'NOI — Net Operating Income',
    short: 'Brutto minus operative Kosten, vor Hypothek und Steuern',
    longDe: 'NOI ist der Jahresertrag aus laufendem Betrieb — vor Finanzierungskosten (Zinsen) und Steuern. Reine Operations-Kennzahl.',
    formula: 'NOI = Bruttoeinnahmen − Plattform-Gebühren − Management − Cleaning − Unterhalt − Kurtaxe',
    example: 'Brutto CHF 92\'000 − 14% Plattform − 5% Mgmt − 8% Cleaning − 1.2% Unterhalt − 2% Kurtaxe = NOI ~CHF 65\'000',
  },
  opex: {
    title: 'OpEx — Operating Expenses',
    short: 'Operative Ausgaben pro Jahr',
    longDe: 'OpEx umfasst alle laufenden Kosten zur Betreibung: Unterhalt, Versicherung, Liegenschaftssteuer, Verwaltungs-Pauschalen, Versorgung.',
    formula: 'Standardannahme bei Kauf: ~1.2% des Kaufpreises p.a.\nBei Miete: Versicherung + Strom + Internet + Verbrauchsmaterial',
    example: 'Kaufpreis CHF 1\'000\'000 → OpEx ~CHF 12\'000/Jahr',
  },
  occupancy: {
    title: 'Auslastung / Occupancy',
    short: 'Anteil der vermieteten Nächte pro verfügbarer Nacht',
    longDe: 'Bei BFS-Daten: Bettenauslastung = belegte Bettennächte ÷ angebotene Bettennächte. Bei STR: vermietete Nächte ÷ verfügbare Nächte. Hochsaison kann 90%+ erreichen, Off-Season fällt teils auf 15-25%.',
    formula: 'Auslastung % = vermietete Nächte ÷ verfügbare Nächte × 100',
    example: 'Verbier Februar: 28 von 28 Tagen vermietet = 100% Auslastung\nVerbier November: 6 von 30 Tagen = 20%',
    caveat: 'Hotel-Auslastung (BFS HESTA) ist oft niedriger als STR-Auslastung — Hotels öffnen ganzjährig auch in toten Phasen, STR-Hosts blockieren Off-Season einfach den Kalender.',
  },
  multiple: {
    title: 'Mietzins-Multiple',
    short: 'Wie oft STR-Brutto-Monat in der Monatsmiete steckt',
    longDe: 'Im Rental-Arbitrage-Modus die wichtigste Kennzahl. Multiple zeigt das Verhältnis zwischen monatlichem STR-Bruttoertrag und der Miete die du an den Eigentümer zahlst.',
    formula: 'Multiple = STR-Brutto pro Monat ÷ Monatsmiete',
    example: 'STR bringt CHF 4\'500/Monat brutto, Miete CHF 1\'800 = Multiple 2.5×',
    caveat: '≥ 2.5× und Break-Even < 12 Monate = Strong Deal\n< 1.5× = Lass die Finger weg',
  },
  breakeven: {
    title: 'Break-Even Occupancy',
    short: 'Minimale Auslastung bei der die Kosten gedeckt sind',
    longDe: 'Break-Even Occupancy zeigt wie viel Auslastung du brauchst um nicht ins Minus zu fallen. Niedrig = sicherer Markt.',
    formula: 'Break-Even-Occ = (Zinsen + OpEx) ÷ (ADR × 365 × (1 − Plattform − Mgmt − Cleaning − Kurtaxe))',
    example: 'Kosten CHF 30\'000/Jahr, Max-Brutto 60\'000 (alles vermietet) → BE = 50%',
  },
  swap: {
    title: '10Y Swap — Risikoloser Referenzzins',
    short: 'Schweizer 10-Jahres-Swap-Satz als Risk-Free-Benchmark',
    longDe: 'Der 10-Jahres-Swap ist der Marktzins den Banken zwischen sich für 10-jährige fixe Zinszahlungen tauschen. Unsere ROI sollte mindestens diesen Zins plus Risiko-Aufschlag (3-5 pp) liefern.',
    formula: 'Spread = CoC − 10Y-Swap',
    example: 'Aktueller 10Y-Swap: 1.35%\nCoC 7% → Spread +5.65 pp = solide Anlage',
  },
  grade: {
    title: 'Grade A/B/C/D — Markt-Ranking',
    short: 'Internes Performance-Ranking pro Markt',
    longDe: 'Grade kombiniert RevPAR, Wachstum, Supply-Stabilität und regulatorisches Risiko in eine Buchstabe-Note.',
    formula: 'A = Top-Performance + Supply-Lock + reguliert sicher\nB = solider Markt\nC = sekundärer Markt\nD = defensiv / nur Eigennutzung',
    example: 'A: Verbier, Zermatt, St. Moritz, Gstaad\nB: Davos, Laax, Klosters\nC: Schaffhausen, Brienz\nD: Olten, Frauenfeld',
  },
  logiernaechte: {
    title: 'Logiernächte',
    short: 'Anzahl Übernachtungen pro Gast — die BFS-Standard-Metrik',
    longDe: 'Die offizielle Schweizer Tourismus-Kennzahl. Eine 4-köpfige Familie die 3 Nächte bleibt = 12 Logiernächte. Wird von BFS HESTA monatlich pro Gemeinde publiziert.',
    formula: 'Logiernächte = Anzahl Gäste × Anzahl Übernachtungen',
    example: 'Zermatt 2025: 1.7M Logiernächte über alle Hotels gesamtjahr',
  },
  kurtaxe: {
    title: 'Kurtaxe',
    short: 'Übernachtungsabgabe pro Gast/Nacht — durchlaufender Posten',
    longDe: 'Die Kurtaxe ist eine kommunale Abgabe pro Gast und Nacht, die du als Vermieter einziehst und an die Gemeinde abführst. Schweizweit zwischen CHF 2.– und CHF 7.– pro Gast/Nacht. Aufwand: monatliche oder quartalsweise Meldung.',
    formula: 'Du erhebst die Kurtaxe vom Gast und führst sie ab. Kein Cash-Effekt für dich, nur Admin.',
    example: 'Zermatt: CHF 4.50 / Erwachsener / Nacht. Familie 4 Personen, 5 Nächte = CHF 90 Kurtaxe.',
    caveat: 'In unserer Calc setzen wir 2% des Brutto als Faustregel an — vereinfacht.',
  },
  cap90: {
    title: '90-Tage-Cap',
    short: 'Kommunale Beschränkung der STR-Vermietungsdauer',
    longDe: 'Kantone oder Städte mit aktivem 90-Tage-Cap (Genf, Stadt Luzern) erlauben Kurzvermietung nur an maximal 90 Tagen pro Jahr. Das macht reine STR-Arbitrage wirtschaftlich unmöglich — die anderen 275 Tage muss das Objekt entweder leer stehen oder regulär vermietet werden.',
    example: 'Genf: 90 Tage × CHF 200 ADR × 80% = CHF 14\'400 Brutto pro Jahr\nNach Mietzins + Kosten typisch negativ.',
    caveat: 'Solche Märkte sind im Scout als 🔴 markiert und der Such-Generator schlägt Alternativ-Märkte vor.',
  },
  zweitwohnung: {
    title: 'Zweitwohnungs-Cap',
    short: '20%-Limit für Neubauten pro Gemeinde',
    longDe: 'Das Zweitwohnungsgesetz (2012) begrenzt den Anteil von Zweitwohnungen auf 20% pro Gemeinde. In Wallis, Graubünden und vielen Berner-Oberland-Gemeinden ist dieser Anteil längst überschritten — kein Neubau zur STR-Nutzung möglich.',
    example: 'Zermatt, Verbier, St. Moritz, Saas-Fee, Lauterbrunnen, Grindelwald, Gstaad — alle gesperrt.',
    caveat: 'Für Bestandsobjekte = Knappheits-Prämie (+3-5% Wertsteigerung p.a.). Für Investoren die kaufen wollen aber: kein Neubau-Markt, nur Sekundärmarkt.',
  },
  trendsetter: {
    title: 'Trendsetter-Index',
    short: 'YoY-Anomalie der letzten 3 Monate gegen Vorjahres-Zeitraum',
    longDe: 'Unsere algorithmische Strategie: welche Märkte haben in den letzten 3 Monaten überraschend mehr Logiernächte als im gleichen Zeitraum des Vorjahres? Identifiziert Aufsteiger 6–12 Monate vor der Branchenpresse.',
    formula: 'Trend % = (letzte 3 Mt Ø ÷ Vorjahres-3 Mt Ø − 1) × 100',
    example: 'Martigny: 8\'000 (Jan-Mär 2026) ÷ 6\'000 (Jan-Mär 2025) − 1 = +33% Breakout',
  },
};
