// Glossar der Fachbegriffe — gelinkt aus dem UI via .glossary-term[data-term="..."]
// Klick öffnet Modal mit Definition + Formel + Beispiel.

const GLOSSARY = {
  adr: {
    title: 'ADR — Average Daily Rate',
    short: 'Durchschnittlicher Preis pro vermieteter Nacht',
    longDe: 'ADR ist der durchschnittliche Preis den ein Gast pro Nacht zahlt — gemittelt über alle vermieteten Nächte in einem Zeitraum.',
    formula: 'ADR = Brutto-Mieteinnahmen ÷ Anzahl vermieteter Nächte',
    example: 'CHF 35\'000 Einnahmen ÷ 140 vermietete Nächte = CHF 250 ADR',
    caveat: '⚠️ Ein Markt-Durchschnitts-ADR sagt allein nichts aus. Ein 4-Zimmer-Chalet kostet 2-3× mehr als ein Studio. Im KPI-Drill siehst du die Verteilung nach Zimmer-Anzahl.',
  },
  revpar: {
    title: 'RevPAR — Revenue per Available Room',
    short: 'Umsatz pro verfügbarer Vermietungs-Nacht',
    longDe: 'RevPAR kombiniert Preis (ADR) und Auslastung in einer Kennzahl. Verfügbar = die Wohnung könnte vermietet werden, nicht ob sie es war.',
    formula: 'RevPAR = ADR × Auslastung (%)\noder = Jahresumsatz ÷ 365 Tage',
    example: 'ADR CHF 250 × 60% Auslastung = RevPAR CHF 150/Nacht',
    caveat: 'Wenn RevPAR niedrig ist aber ADR hoch → Auslastungsproblem. Wenn ADR niedrig aber RevPAR OK → Markt mit hoher Auslastung.',
  },
  yoy: {
    title: 'YoY — Year-over-Year',
    short: 'Vergleich zum gleichen Zeitraum des Vorjahres',
    longDe: 'YoY (Year-over-Year) misst die Veränderung gegenüber dem identischen Vorjahres-Zeitraum. Eliminiert Saisonalitäts-Effekte: Januar vs Januar, nicht Januar vs Dezember.',
    formula: 'YoY-Δ = (aktuell − Vorjahr) ÷ Vorjahr × 100%',
    example: 'Jan 2026: 8\'000 Logiernächte\nJan 2025: 6\'000 Logiernächte\nYoY = +33%',
  },
  pp: {
    title: 'pp — Prozentpunkte',
    short: 'Absolute Differenz zweier Prozentwerte',
    longDe: 'Prozentpunkte (pp) drücken die rohe Differenz zwischen zwei Prozent-Werten aus — nicht das Verhältnis. Wichtig bei Auslastung und Zinssätzen.',
    formula: 'pp = neuer % − alter %',
    example: 'Auslastung von 60% auf 64% gestiegen = +4 pp\n(NICHT +6.7%, das wäre der relative Anstieg)',
  },
  coc: {
    title: 'CoC — Cash-on-Cash Return',
    short: 'Jährlicher Netto-Cashflow ÷ tatsächlich eingesetztes Eigenkapital',
    longDe: 'CoC ist die wichtigste Kennzahl für Cashflow-Investoren. Sie ignoriert Wertsteigerung und misst nur den tatsächlichen Geldrückfluss auf das eingesetzte Kapital.',
    formula: 'CoC = (NOI − Hypothekarzins) ÷ Eigenkapital × 100%',
    example: 'CHF 25\'000 Cashflow ÷ CHF 250\'000 Eigenkapital = 10% CoC',
    caveat: 'Ab 7% gilt als sehr gut. Vergleich mit 10Y-Swap (~1.35%) — alles über +5 Prozentpunkte Spread ist solide.',
  },
  cap: {
    title: 'Cap Rate — Capitalization Rate',
    short: 'Bruttorendite vor Finanzierung',
    longDe: 'Cap Rate misst die Rendite einer Liegenschaft ohne Hypothek. Wichtig für den Vergleich von Objekten unabhängig von der Finanzierungs-Struktur.',
    formula: 'Cap Rate = NOI ÷ Kaufpreis × 100%',
    example: 'CHF 50\'000 NOI ÷ CHF 1\'250\'000 Kaufpreis = 4% Cap Rate',
    caveat: 'Im Rent-Modus zeigen wir stattdessen den Mietzins-Multiple (STR-Brutto-Monat / Mietzins) — sinnvoller für Arbitrage.',
  },
  noi: {
    title: 'NOI — Net Operating Income',
    short: 'Brutto minus operative Kosten, vor Hypothek und Steuern',
    longDe: 'NOI ist der Jahresertrag aus laufendem Betrieb — vor Finanzierungskosten (Zinsen) und Steuern. Reine Operations-Kennzahl.',
    formula: 'NOI = Bruttoeinnahmen − Plattform-Gebühren − Management − Cleaning − Unterhalt − Kurtaxe',
    example: 'Brutto CHF 92\'000 − 14% Plattform − 5% Mgmt − 8% Cleaning − 1.2% Unterhalt − 2% Kurtaxe = NOI ~CHF 65\'000',
  },
  opex: {
    title: 'OpEx — Operating Expenses',
    short: 'Operative Ausgaben pro Jahr',
    longDe: 'OpEx umfasst alle laufenden Kosten zur Betreibung: Unterhalt, Versicherung, Liegenschaftssteuer, Verwaltungs-Pauschalen, Versorgung.',
    formula: 'Standardannahme bei Kauf: ~1.2% des Kaufpreises p.a.\nBei Miete: Versicherung + Strom + Internet + Verbrauchsmaterial',
    example: 'Kaufpreis CHF 1\'000\'000 → OpEx ~CHF 12\'000/Jahr',
  },
  occupancy: {
    title: 'Auslastung / Occupancy',
    short: 'Anteil der vermieteten Nächte pro verfügbarer Nacht',
    longDe: 'Bei BFS-Daten: Bettenauslastung = belegte Bettennächte ÷ angebotene Bettennächte. Bei STR: vermietete Nächte ÷ verfügbare Nächte. Hochsaison kann 90%+ erreichen, Off-Season fällt teils auf 15-25%.',
    formula: 'Auslastung % = vermietete Nächte ÷ verfügbare Nächte × 100',
    example: 'Verbier Februar: 28 von 28 Tagen vermietet = 100% Auslastung\nVerbier November: 6 von 30 Tagen = 20%',
    caveat: 'Hotel-Auslastung (BFS HESTA) ist oft niedriger als STR-Auslastung — Hotels öffnen ganzjährig auch in toten Phasen, STR-Hosts blockieren Off-Season einfach den Kalender.',
  },
  multiple: {
    title: 'Mietzins-Multiple',
    short: 'Wie oft STR-Brutto-Monat in der Monatsmiete steckt',
    longDe: 'Im Rental-Arbitrage-Modus die wichtigste Kennzahl. Multiple zeigt das Verhältnis zwischen monatlichem STR-Bruttoertrag und der Miete die du an den Eigentümer zahlst.',
    formula: 'Multiple = STR-Brutto pro Monat ÷ Monatsmiete',
    example: 'STR bringt CHF 4\'500/Monat brutto, Miete CHF 1\'800 = Multiple 2.5×',
    caveat: '≥ 2.5× und Break-Even < 12 Monate = Strong Deal\n< 1.5× = Lass die Finger weg',
  },
  breakeven: {
    title: 'Break-Even Occupancy',
    short: 'Minimale Auslastung bei der die Kosten gedeckt sind',
    longDe: 'Break-Even Occupancy zeigt wie viel Auslastung du brauchst um nicht ins Minus zu fallen. Niedrig = sicherer Markt.',
    formula: 'Break-Even-Occ = (Zinsen + OpEx) ÷ (ADR × 365 × (1 − Plattform − Mgmt − Cleaning − Kurtaxe))',
    example: 'Kosten CHF 30\'000/Jahr, Max-Brutto 60\'000 (alles vermietet) → BE = 50%',
  },
  swap: {
    title: '10Y Swap — Risikoloser Referenzzins',
    short: 'Schweizer 10-Jahres-Swap-Satz als Risk-Free-Benchmark',
    longDe: 'Der 10-Jahres-Swap ist der Marktzins den Banken zwischen sich für 10-jährige fixe Zinszahlungen tauschen. Unsere ROI sollte mindestens diesen Zins plus Risiko-Aufschlag (3-5 pp) liefern.',
    formula: 'Spread = CoC − 10Y-Swap',
    example: 'Aktueller 10Y-Swap: 1.35%\nCoC 7% → Spread +5.65 pp = solide Anlage',
  },
  grade: {
    title: 'Grade A/B/C/D — Markt-Ranking',
    short: 'Internes Performance-Ranking pro Markt',
    longDe: 'Grade kombiniert RevPAR, Wachstum, Supply-Stabilität und regulatorisches Risiko in eine Buchstabe-Note.',
    formula: 'A = Top-Performance + Supply-Lock + reguliert sicher\nB = solider Markt\nC = sekundärer Markt\nD = defensiv / nur Eigennutzung',
    example: 'A: Verbier, Zermatt, St. Moritz, Gstaad\nB: Davos, Laax, Klosters\nC: Schaffhausen, Brienz\nD: Olten, Frauenfeld',
  },
  logiernaechte: {
    title: 'Logiernächte',
    short: 'Anzahl Übernachtungen pro Gast — die BFS-Standard-Metrik',
    longDe: 'Die offizielle Schweizer Tourismus-Kennzahl. Eine 4-köpfige Familie die 3 Nächte bleibt = 12 Logiernächte. Wird von BFS HESTA monatlich pro Gemeinde publiziert.',
    formula: 'Logiernächte = Anzahl Gäste × Anzahl Übernachtungen',
    example: 'Zermatt 2025: 1.7M Logiernächte über alle Hotels gesamtjahr',
  },
  kurtaxe: {
    title: 'Kurtaxe',
    short: 'Übernachtungsabgabe pro Gast/Nacht — durchlaufender Posten',
    longDe: 'Die Kurtaxe ist eine kommunale Abgabe pro Gast und Nacht, die du als Vermieter einziehst und an die Gemeinde abführst. Schweizweit zwischen CHF 2.– und CHF 7.– pro Gast/Nacht. Aufwand: monatliche oder quartalsweise Meldung.',
    formula: 'Du erhebst die Kurtaxe vom Gast und führst sie ab. Kein Cash-Effekt für dich, nur Admin.',
    example: 'Zermatt: CHF 4.50 / Erwachsener / Nacht. Familie 4 Personen, 5 Nächte = CHF 90 Kurtaxe.',
    caveat: 'In unserer Calc setzen wir 2% des Brutto als Faustregel an — vereinfacht.',
  },
  cap90: {
    title: '90-Tage-Cap',
    short: 'Kommunale Beschränkung der STR-Vermietungsdauer',
    longDe: 'Kantone oder Städte mit aktivem 90-Tage-Cap (Genf, Stadt Luzern) erlauben Kurzvermietung nur an maximal 90 Tagen pro Jahr. Das macht reine STR-Arbitrage wirtschaftlich unmöglich — die anderen 275 Tage muss das Objekt entweder leer stehen oder regulär vermietet werden.',
    example: 'Genf: 90 Tage × CHF 200 ADR × 80% = CHF 14\'400 Brutto pro Jahr\nNach Mietzins + Kosten typisch negativ.',
    caveat: 'Solche Märkte sind im Scout als 🔴 markiert und der Such-Generator schlägt Alternativ-Märkte vor.',
  },
  zweitwohnung: {
    title: 'Zweitwohnungs-Cap',
    short: '20%-Limit für Neubauten pro Gemeinde',
    longDe: 'Das Zweitwohnungsgesetz (2012) begrenzt den Anteil von Zweitwohnungen auf 20% pro Gemeinde. In Wallis, Graubünden und vielen Berner-Oberland-Gemeinden ist dieser Anteil längst überschritten — kein Neubau zur STR-Nutzung möglich.',
    example: 'Zermatt, Verbier, St. Moritz, Saas-Fee, Lauterbrunnen, Grindelwald, Gstaad — alle gesperrt.',
    caveat: 'Für Bestandsobjekte = Knappheits-Prämie (+3-5% Wertsteigerung p.a.). Für Investoren die kaufen wollen aber: kein Neubau-Markt, nur Sekundärmarkt.',
  },
  mgmt: {
    title: 'Mgmt — Management',
    short: 'Verwaltungs-Pauschale',
    longDe: 'Verwaltungs-Anteil — typischerweise 5% bei Self-Management (du machst alles selber: Kommunikation, Pricing, kleine Reparaturen). Bei externen Property Managern: 15-25%. Im Tool default 5%.',
    formula: 'Mgmt-Kosten = Brutto × Mgmt-Prozent',
    example: 'Brutto CHF 20\'000 × 5% = CHF 1\'000 Mgmt-Kosten',
  },
  nk: {
    title: 'NK — Nebenkosten',
    short: 'Strom, Wasser, Internet, Müllabfuhr',
    longDe: 'Nebenkosten sind die laufenden Betriebskosten neben dem Mietzins: Strom, Wasser, Internet, Heizung, Müllabfuhr, Gemeinde-Steuern. Je nach Mietvertrag bereits im Mietzins enthalten („inkl. NK") oder separat abzurechnen.',
    formula: 'NK ≈ CHF 180–250/Monat für eine 2.5-3.5-Zimmer-Wohnung (ohne Heizung im Winter höher)',
    example: 'Studio: ~CHF 180/Mt · 3.5Z: ~CHF 200/Mt · Premium-Chalet: ~CHF 250+/Mt',
  },
  str: {
    title: 'STR — Short-Term Rental',
    short: 'Kurzzeitvermietung',
    longDe: 'Short-Term Rental (STR) bezeichnet kurzfristige Vermietung über Plattformen wie Airbnb, Booking.com, Vrbo — typischerweise 1–30 Nächte. Abgrenzung zu Mid-Term (30-180 Tage) und Long-Term (regulärer Mietvertrag ab 6 Mt.).',
  },
  putzgebuehr: {
    title: 'Putzgebühr',
    short: 'Was der Gast pro Aufenthalt zusätzlich zahlt',
    longDe: 'Standard-Praxis auf Airbnb/Booking: separate Position oben drauf, wird vom Gast bezahlt. Du leitest sie 1:1 an deine Putzkraft weiter — kein Verlust, aber auch kein Gewinn. Höhe richtet sich nach Wohnungsgröße + Bettwäsche-Wechsel.',
    formula: 'Studio 70 · 2.5Z 90 · 3.5Z 110 · 4.5Z 130 · 5.5Z+ 150 CHF inkl. Bettwäsche',
    example: 'Gast bucht 4 Nächte in 2.5Z: zahlt 4×ADR + 90 CHF Putzgebühr. Du gibst die 90 CHF an deine Putzfrau.',
  },
  konfidenz: {
    title: 'Konfidenz / Genauigkeit',
    short: 'Wie nahe an der Realität liegen unsere Schätzungen?',
    longDe: 'Das Tool gibt eine ehrliche Größenordnung — keine Punkt-Prognose. Auf <strong>Markt-Ebene</strong> (Durchschnitt einer ganzen Gemeinde) sind absolute Cashflow-Werte ±30–50% Streuung. Sobald du <strong>konkret wirst</strong> (deine Wohnung, dein Mietzins, deine Putzfrau, dein ADR aus Booking) wird das Tool deutlich präziser — die Streuung sinkt von ±50% auf ±10–15%.',
    formula: '🟢 Verlässlich: relative Vergleiche zwischen Märkten, Sensitivität (z.B. „+10% Auslastung"), Break-Even-Punkte\n🟡 Mittel: absolute Größenordnung („sind wir bei CHF 10k oder 50k Cashflow?")\n🔴 Schwach: konkreter Franken-Wert einer einzelnen Wohnung — solange du nur den Markt anschaust, nicht ein konkretes Objekt',
    example: 'Markt-Schnitt sagt CHF 5\'000/Jahr Cashflow → Realität für eine zufällige Wohnung in dem Markt: CHF 3\'500–7\'000. Wenn du in der Custom-Karte deinen tatsächlichen ADR (z.B. CHF 280 statt Markt-Schnitt 245), deine Auslastung aus Airbnb-Statistiken und deinen echten Mietzins einträgst, schrumpft die Spanne auf CHF 4\'500–5\'500.',
    caveat: 'Quellen der Streuung: ADR/Listings sind Markt-Modelle (BFS HESTA enthält nur Hotellerie, keine Ferienwohnungs-Preise) · Lage-Premium innerhalb einer Gemeinde fehlt · individuelle Wohnungs-Qualität (Renovation, Aussicht, Balkon, Ski-in/out) variiert ±30% · Saison-Spread bei dual-saisonalen Märkten bis 4× zwischen Hoch- und Tiefmonat.',
    improve: '<strong>Was du tun kannst, um aus ±50% auf ±10–15% zu kommen:</strong><ul class="list-disc ml-5 mt-1 space-y-1"><li><strong>Konkreten ADR setzen:</strong> Custom-Karte → ADR-Slider auf den Preis, den vergleichbare Wohnungen tatsächlich auf Airbnb/Booking verlangen (3 Listings im selben Quartier mitteln).</li><li><strong>Auslastung verfeinern:</strong> Erst nur die Monate auswählen die für dich relevant sind (Saisonalität-Chart klickbar). Bei dual-saisonalen Märkten oder wenn du nur Hauptsaison vermieten willst sinkt die Streuung massiv.</li><li><strong>Mietzins exakt eintragen:</strong> Statt Default-Schätzung den tatsächlichen Mietvertrag-Wert — das ist meist der grösste Streuungs-Treiber.</li><li><strong>Putzkraft + Verwaltung anpassen:</strong> Eigene Putzfrau-Stundenlohn × geschätzte Stunden statt Default 110 CHF.</li><li><strong>Plattform-Modus wählen:</strong> Host-only (CH-Default) oder Split-Fee (3% + 14% Gast) — macht 8–11% Cashflow-Unterschied.</li><li><strong>Wohnungstyp + Profil:</strong> 1Z/2.5Z/3.5Z/4.5Z/5.5Z+ Toggle setzt automatisch realistische Putz- und Nebenkosten-Defaults.</li></ul><div class="mt-2 text-xs text-[color:var(--muted)]">Faustregel: jeder konkrete Input ersetzt eine Modell-Annahme. Je mehr du selbst weißt, desto enger die Spanne.</div>',
  },
  trendsetter: {
    title: 'Trendsetter-Index',
    short: 'YoY-Anomalie der letzten 3 Monate gegen Vorjahres-Zeitraum',
    longDe: 'Unsere algorithmische Strategie: welche Märkte haben in den letzten 3 Monaten überraschend mehr Logiernächte als im gleichen Zeitraum des Vorjahres? Identifiziert Aufsteiger 6–12 Monate vor der Branchenpresse.',
    formula: 'Trend % = (letzte 3 Mt Ø ÷ Vorjahres-3 Mt Ø − 1) × 100',
    example: 'Martigny: 8\'000 (Jan-Mär 2026) ÷ 6\'000 (Jan-Mär 2025) − 1 = +33% Breakout',
  },
};
